version: '2'

services:
  speedtest:
    build: .
    mem_limit: 512M
    volumes:
      - ./db:/app/db
    environment:
      - INTERVAL_MIN=15

  speedtest_web-ui:
    build: .
    entrypoint: python ./web/web.py
    mem_limit: 512M
    volumes:
      - ./db:/app/db
    ports:
      - 8081:8081